Drop the aspell dictionaries that were removed from nixpkgs
     error: 'aspellDicts.en-computers' has been removed as upstream url pointed to a gambling website.