Fix build error caused by `nerdfonts` packaging change.
Addresses the following build error:

```
       error: nerdfonts has been separated into individual font packages under the namespace nerd-fonts.
       For example change:
         fonts.packages = [
           ...
           (pkgs.nerdfonts.override { fonts = [ "0xproto" "DroidSansMono" ]; })
         ]
       to
         fonts.packages = [
           ...
           pkgs.nerd-fonts._0xproto
           pkgs.nerd-fonts.droid-sans-mono
         ]
       or for all fonts
         fonts.packages = [ ... ] ++ builtins.filter lib.attrsets.isDerivation (builtins.attrValues pkgs.nerd-fon
       ...
```

Note that previously all nerdfonts were being installed; this commit changes to
a much smaller subset of fonts.